name: dotstar-viewer
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.7
  - pyqt=5
  - numpy>=1.21.0
  - pandas>=1.3.0
  - pyyaml>=5.4.0
  - pillow>=8.3.0
  - matplotlib>=3.4.0
  - scipy>=1.7.0
  - h5py>=3.1.0
  - netcdf4>=1.5.0
  - pytorch>=1.9.0
  - pip
  - pip:
    - toml>=0.10.0
    - pyarrow>=5.0.0
    - safetensors>=0.2.0
    - astropy>=4.3.0
